### ISSUE TITLE
ssr加速好像不起作用

### ISSUE THREAD

**Issue by erguotou520** [dabiaoge/lkl#1]
shadowsocksr的docker启动命令为
```bash
docker run -d -e PASSWORD=password -p 51348:51348 --name ssr breakwa11/shadowsocksr
```
lkl的启动命令为
```bash
docker run -d --privileged --link ssr:myhost -e TARGET_HOST=ssr.erguotou.me -e TARGET_PORT=51348 -p 8888:8888 --name lkl wuqz/lkl:latest
```
前后打开youtube，发现没什么变化
vps支持tun

**Comment by dabiaoge** [comment]
如果ssr和lkl在同一个服务器上，推荐运行lkl的时候执行下面命令：
docker run -d --privileged --link ssr:myhost -e **TARGET_HOST=myhost** -e TARGET_PORT=51348 -p 8888:8888 --name lkl wuqz/lkl:latest
然后ssr客户端需要连接你服务器(ssr.erguotou.me)的8888端口。（而不是51348端口），
试试看！

**Comment by erguotou520** [comment]
myhost 到底啥意义？第一个是标志，第二个不是ssr host么？

**Comment by dabiaoge** [comment]
设置--link ssr:myhost   那么，ssr这个服务器（docker容器名）的别名就是myhost了。   TARGET_HOST=myhost就是把流量转到这个服务器喽。

**Comment by erguotou520** [comment]
嗯 看到效果了，Nice project!
