### ISSUE TITLE
ssr不管用

### ISSUE THREAD

**Issue by lewisxy** [dabiaoge/lkl#2]
ss和ssr在一个服务器上，ss用这个指令ok了
`docker run -d -e PASSWORD=sspass -p 8388:8388 --name shadowsocks wuqz/sss:latest`
`docker run -d --privileged --link shadowsocks:myhost -e TARGET_HOST=myhost -e TARGET_PORT=8388 -p 8888:8888 --name lkl wuqz/lkl:latest`

ssr使用的是自己制作的镜像，无加速测试成功，源端口是11120tcp和11120udp，使用以下命令打开加速
`docker run -d --privileged --link ssr1:myhost -e TARGET_HOST=myhost -e TARGET_PORT=11120 -p 11121:11121 --name lkl_ssr wuqz/lkl:latest`
不管用
下面是`docker ps`输出结果
```
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                                NAMES
62758a635b23        wuqz/lkl:latest     "/bin/sh -c /root/lk   About an hour ago   Up About an hour    0.0.0.0:11121->11121/tcp                             lkl_ssr
13054299189f        wuqz/lkl:latest     "/bin/sh -c /root/lk   About an hour ago   Up About an hour    0.0.0.0:8888->8888/tcp                               lkl_ss
0f8ea692d022        ssr:v0.3            "ssserver -s 0.0.0.0   About an hour ago   Up About an hour    0.0.0.0:11120->11120/udp, 0.0.0.0:11120->11120/tcp   ssr1
86e3b5b55157        wuqz/sss:latest     "/bin/sh -c 'ssserve   45 hours ago        Up 45 hours         0.0.0.0:8388->8388/tcp                               shadowsocks
```
经过查看docker的log发现客户端向服务器11121端口发送的包ssr收不到，因此感觉是加速器出了问题

**Comment by dabiaoge** [comment]
docker run -d --privileged --link ssr1:myhost -e TARGET_HOST=myhost -e TARGET_PORT=11120 -p  8888:11121 --name lkl_ssr wuqz/lkl:latest
lkl默认开放的端口，就是8888.  你需要映射8888到11121，试试看！

**Comment by dabiaoge** [comment]
如果你要修改默认开放的端口，请使用BIND_PORT这个变量，这样写，也是可以的哦
docker run -d --privileged --link ssr1:myhost -e TARGET_HOST=myhost -e TARGET_PORT=11120 -e BIND_PORT=11121  -p 11121:11121 --name lkl_ssr wuqz/lkl:latest

**Comment by lewisxy** [comment]
搞定了，非常感谢！
-p 端口映射是<主机>:<container>所以应该是 **-p 11121:8888**

**Comment by dabiaoge** [comment]
谢谢提醒。客气了。
